### ISSUE TITLE
Intro Text

### ISSUE THREAD

**Issue by jsonin** [goinvo/DigitalHealthServiceComponents#2]
This is can be the introduction text, which is the 1st "layer", ie is visible when the screen loads. Then we have some intro + 1st layer.
Might be too much text!

> The **Digital Health Connections model** is a representation of the system of services that can make up digital health software.
> 
> Much like the [OSI model](https://en.wikipedia.org/wiki/OSI_model), the Digital Health Connections model is a stack of common services, functions, elements, and terms.  The model partitions the information flow into 10 abstraction layers, from the common data elements to the highest level of representation of information occurs, with the Patient Health Manager.  
> 
> Questions and issues: 
> - This is shown as a linear flow. However, it’s not linear or completely hierarchal. Do you have any suggestions on showing non-linearity?  
> - Trauma, surgery, and other medical disciplines may prescribe to parts of this model. We need to show those disciplines in the model.  
> 
> This is an [open source project](https://github.com/goinvo/DigitalHealthServiceComponents), licensed under the Apache 2.0 license. Please email us feedback: [hello@goinvo.com](mailto:hello@goinvo.com).

**Comment by poofytoo** [comment]
This text has been updated here, and can be previewed here! [https://goinvo.github.io/DigitalHealthServiceComponents/](https://goinvo.github.io/DigitalHealthServiceComponents/)

Feel free to reopen this issue if there edits/changes you'd like to make.
