### ISSUE TITLE
My header stinks

### ISSUE THREAD

**Issue by jsonin** [goinvo/DigitalHealthServiceComponents#3]
Everything above the stack diagram viz _**stinks**_.
It kills the vibe, makes it feel old, and is limp content.

Just complaining.
Will stew on how to actually Design it (or delete it, put the idea somewhere else, or...).

**Comment by jsonin** [comment]
What if the header went away, and the text in the header looked like, behaved like the layer sections... so on page load, the diagram would be flush top, and the stack 'title:' "Digital Health Connections Model"

description: (
<div>
<p>
The Digital Health Connections Model is a representation of the system of services that can make up digital health software.

Much like the OSI model, the Digital Health Connections model is a stack of common services, functions, elements, and terms.The model partitions the information flow into 10 abstraction layers, from the common data elements to the highest level of representation of information occurs, with the Patient Health Manager.

This is an open source project, licensed under the Apache 2.0 license.
Please email us feedback: hello@goinvo.com.
</p>

Then the moment one scrolls or touches anything else on the page, that section scrolls up to reveal the next and top-most layer (Health Manager).

?

**Comment by poofytoo** [comment]
I think that makes sense. I'll update that.

**Comment by poofytoo** [comment]
Were you thinking something like 

![image](https://user-images.githubusercontent.com/276204/150207461-b5a9d779-d0a0-4777-a0e6-662850025395.png)

**Comment by jsonin** [comment]
Yes, way better.
Hell, do we even need the big blue banner?

**Comment by jsonin** [comment]
Also, the BioMetrics/Results is the 2nd layer... the Health Manager is the top-most abstraction layer.

**Comment by poofytoo** [comment]
Wow. Can't believe my mind just completely wooshed over that. Here it is updated. 

![image](https://user-images.githubusercontent.com/276204/150280737-c0c5c5d9-7d53-4616-a9fa-4129e4a87052.png)
