### ISSUE TITLE
mobile or "thinner" browser view: no description showing up

### ISSUE THREAD

**Issue by jsonin** [goinvo/DigitalHealthServiceComponents#4]
![image](https://user-images.githubusercontent.com/106187/149449985-24f9c962-8f12-4a61-8c51-2b57701efba2.png)

on chrome or safari

**Comment by poofytoo** [comment]
![image](https://user-images.githubusercontent.com/276204/150284684-a43140ce-1c4e-41d0-be9c-d6edb85f85b9.pn

Still thinking about this one...

**Comment by poofytoo** [comment]
This now has the interaction we discussed- tapping on one of these will bring the bottom modal up
