### ISSUE TITLE
Mobile Alignment Issues

### ISSUE THREAD

**Issue by poofytoo** [goinvo/DigitalHealthServiceComponents#5]
Navigation (next/prev buttons) on the modal pop-out window are mis-aligned when there's only one of them (i.e. no next or no prev).
On safari mobile, the behavior is bizarre because in the newest versions of safari, the address bar is on the bottom, causing some super-weird behavior when you scroll within the modal pop-out.

**Comment by poofytoo** [comment]
Some quick thoughts- chrome doesn't have a buffer at the bottom, and so content is pushed a little too close to the bottom. Maybe the solution is to position fix the modal using `top` instead of `bottom` and use `vh` to determine a set distance, with a healthy buffer on the bottom.

**Comment by jsonin** [comment]
Also an alignment/show bug in mobile that the top 2 "layers" of clinician health manager + patient health manager (and the 2 extra ovals for stakeholder health manager) dont appear.... they do appear in a full-width browser on da lappy.

**Comment by jsonin** [comment]
If content is really close to the bottom of the screen = ok problem to have. it almost acts as a stickie filter/nav bar on the bottom of screens....

**Comment by jsonin** [comment]
![image](https://user-images.githubusercontent.com/106187/150542821-500c38ff-1ff1-4cf7-aa7f-65543a829a90.png)
Should be centered + each oval independently clickable (instigates a layer description)

**Comment by jsonin** [comment]
+ common data elements layer
![image](https://user-images.githubusercontent.com/106187/150549919-f0bbd201-3102-483a-9ba5-67854e64b96b.png)

Dotted line not required (nice to have).

**Comment by poofytoo** [comment]
> ![image](https://user-images.githubusercontent.com/106187/150542821-500c38ff-1ff1-4cf7-aa7f-65543a829a90.png) Should be centered + each oval independently clickable (instigates a layer description)

Yep- I'll get right on this. This centering is difficult for real estate reasons, so I'm thinking of doing an interaction where it starts out aligned (text is cut off on the right) and as you scroll down, the whole stack moves to the left. It's a little bizarre, but I think it could work.

**Comment by jsonin** [comment]
![image](https://user-images.githubusercontent.com/106187/150597043-14721e46-eb4f-4a9c-a7e6-3002dbe3e142.png)
1600 width required for desktop "mode" to kick in.

**Comment by poofytoo** [comment]
Just updating you for interaction with the centering, and also shows that each oval is independently clickable now and brings up the dialog (in mobile view)

![Jan-24-2022 02-54-56](https://user-images.githubusercontent.com/276204/150743086-dd6b6325-204a-42ab-a0c5-27a59d3601be.gif)

**Comment by poofytoo** [comment]
![image](https://user-images.githubusercontent.com/276204/153977878-9fc9a4d7-797a-45cf-82ee-0eab702e8ba3.png)

Added common data elements layer at the bottom. I use the text-on-the-right syntax instead of the perspective text. what do you think?
