### ISSUE TITLE
Desktop Width Mode

### ISSUE THREAD

**Issue by poofytoo** [goinvo/DigitalHealthServiceComponents#6]
![image](https://user-images.githubusercontent.com/106187/150597043-14721e46-eb4f-4a9c-a7e6-3002dbe3e142.png)
1600 width required for desktop "mode" to kick in.

_Originally posted by @jsonin in https://github.com/goinvo/DigitalHealthServiceComponents/issues/5#issuecomment-1018843540_

**Comment by poofytoo** [comment]
Sorry, just opening a new issue for this. For clarification, did you want it to KICK in at 1600 width, instead of what it is now? (which is something like 1300px I think)

**Comment by jsonin** [comment]
Sry, I'll be more clear.

On Chrome, the "desktop" view is instigated at 1,600 pixels.
On Safari, it's 1,300.

There seems to be a 300 pixel gutter on the right side, pushing the required width to be 1,600.
And there is also a gutter/padding on Safari. Can we nuke it so even at 1k is opens up?
![image](https://user-images.githubusercontent.com/106187/151024317-6c2371c4-9b79-4828-9698-15f90ef41745.png)

**Comment by jsonin** [comment]
Whoa, this is cool... a wiggle waggle (cool that the line is attached to the object, hence the dotted line following the layer) when scrolling down, after a layer description window has been instigated.

No fix needed, just seeing it.
![image](https://user-images.githubusercontent.com/106187/151028730-28d393e6-b6aa-4789-b6c1-8243a7927205.png)

**Comment by poofytoo** [comment]
Page is significantly more responsive, and only converts to mobile at under 960px

https://user-images.githubusercontent.com/276204/153973810-8f4dd863-681b-43b3-89c1-0e03e18a4ecf.mp4
